server:
  port: 15030

spring:
  profiles:
    include:
      - db
      - encrypt
      - swagger
      - kafka
      - jwt

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

# logger
logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: trace
