server:
  port: 15010

spring:
  application:
    name: auth-server

  # application-oauth
  profiles:
    include:
      - oauth
      - db
      - swagger

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug

feign:
  hystrix:
    enabled: true
